// Auto-generated by build-env.js
window.__ENV__ = window.__ENV__ || {
  VITE_SUPABASE_URL: 'https://pyinmcinjcyelavkuhfl.supabase.co',
  VITE_SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.test'
};
console.log('✓ Config carregado', window.__ENV__);