// Auto-generated by build-env.js - Carrega variáveis de ambiente sincronamente
window.__ENV__ = window.__ENV__ || {
  VITE_SUPABASE_URL: '',
  VITE_SUPABASE_KEY: ''
};
console.log('✓ Variáveis de ambiente carregadas via config-loader');