#!/usr/bin/env node

// build-env.js - Gera config-loader.js com variáveis de ambiente sincronamente
const fs = require('fs');
const path = require('path');

// Verificar TODAS as variáveis disponíveis
console.log('🔍 Todas as variáveis com VITE ou SUPABASE:');
Object.keys(process.env)
  .filter(key => key.includes('VITE') || key.includes('SUPABASE'))
  .forEach(key => console.log(`  ${key}: ${process.env[key] ? '✓' : '✗'}`));

// Na Vercel, as variáveis estão prefixadas com NEXT_PUBLIC_
const supabaseUrl = process.env.NEXT_PUBLIC_VITE_SUPABASE_URL || 
                     process.env.VITE_SUPABASE_URL || 
                     process.env.SUPABASE_URL ||
                     '';

const supabaseKey = process.env.NEXT_PUBLIC_VITE_SUPABASE_KEY || 
                    process.env.VITE_SUPABASE_KEY || 
                    process.env.SUPABASE_KEY ||
                    '';

console.log('\n📦 Variáveis encontradas:');
console.log('  VITE_SUPABASE_URL:', supabaseUrl ? '✓ ' + supabaseUrl.substring(0, 30) + '...' : '✗');
console.log('  VITE_SUPABASE_KEY:', supabaseKey ? '✓ ' + supabaseKey.substring(0, 30) + '...' : '✗');

// Gerar config-loader.js - injetar variáveis SINCRONAMENTE no window
const loaderContent = `// Auto-generated by build-env.js
window.__ENV__ = window.__ENV__ || {
  VITE_SUPABASE_URL: '${supabaseUrl}',
  VITE_SUPABASE_KEY: '${supabaseKey}'
};
console.log('✓ Config carregado', window.__ENV__);`;

const loaderPath = path.join(__dirname, 'js', 'config-loader.js');
fs.writeFileSync(loaderPath, loaderContent);
console.log('\n✅ config-loader.js gerado com sucesso');
