#!/usr/bin/env node

// build-env.js - Substitui variáveis de ambiente no HTML durante o build
const fs = require('fs');
const path = require('path');

// Na Vercel, as variáveis estão prefixadas com NEXT_PUBLIC_
const supabaseUrl = process.env.NEXT_PUBLIC_VITE_SUPABASE_URL || process.env.VITE_SUPABASE_URL || '';
const supabaseKey = process.env.NEXT_PUBLIC_VITE_SUPABASE_KEY || process.env.VITE_SUPABASE_KEY || '';

console.log('🔍 Buscando variáveis de ambiente:');
console.log('  NEXT_PUBLIC_VITE_SUPABASE_URL:', supabaseUrl ? '✓' : '✗');
console.log('  NEXT_PUBLIC_VITE_SUPABASE_KEY:', supabaseKey ? '✓' : '✗');

// 1. Gerar env.js (fallback)
const envContent = `
// Auto-generated by build-env.js - DO NOT EDIT
window.__ENV__ = {
  VITE_SUPABASE_URL: '${supabaseUrl}',
  VITE_SUPABASE_KEY: '${supabaseKey}'
};
`;

const envJsPath = path.join(__dirname, 'js', 'env.js');
fs.writeFileSync(envJsPath, envContent.trim());
console.log('✅ Variáveis de ambiente geradas em js/env.js');

// 2. Substituir placeholders no index.html
const indexHtmlPath = path.join(__dirname, 'index.html');
let indexHtmlContent = fs.readFileSync(indexHtmlPath, 'utf8');

indexHtmlContent = indexHtmlContent.replace('__VITE_SUPABASE_URL__', supabaseUrl);
indexHtmlContent = indexHtmlContent.replace('__VITE_SUPABASE_KEY__', supabaseKey);

fs.writeFileSync(indexHtmlPath, indexHtmlContent);
console.log('✅ Variáveis injetadas em index.html');

// 3. Substituir placeholders no login.html
const loginHtmlPath = path.join(__dirname, 'login.html');
let loginHtmlContent = fs.readFileSync(loginHtmlPath, 'utf8');

loginHtmlContent = loginHtmlContent.replace('__VITE_SUPABASE_URL__', supabaseUrl);
loginHtmlContent = loginHtmlContent.replace('__VITE_SUPABASE_KEY__', supabaseKey);

fs.writeFileSync(loginHtmlPath, loginHtmlContent);
console.log('✅ Variáveis injetadas em login.html');
